services:
  goatak:
    image: ghcr.io/kdudkov/goatak_server:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    environment:
      - SRV_HOST=adibi.lakida.me
    ports:
      - "8080:8080"
      - "8443:8443"
      - "8088:8088"
      - "8089:8089"
      - "8446:8446"
      - "8999:8999"
      - "8999:8999/udp"
    volumes:
      - /home/alakida/goatak_data/cert/files:/app/cert/files
      - /home/alakida/goatak_data/data:/app/data
      - ./goatak_server.yml:/app/goatak_server.yml
